version: '3'

services:
  php:
    build:
      context: ./Docker/php
    volumes:
      - /Users/ruthnewman/documents/php-docker-app/www:/var/www/app/public/
    working_dir: /
  apache:
    build:
      context: ./Docker/apache
    volumes:
      - /Users/ruthnewman/documents/php-docker-app/www:/var/www/app/public/
    ports:
      - 8080:80
    links:
      - php

